method: td  # Need to add a detector
model:
  backbone:
    type: CSPNeXt
    model_name: cspnext_p5
    freeze_bn_stats: false
    freeze_bn_weights: false
    expand_ratio: 0.5
    deepen_factor: 0.67
    widen_factor: 0.75
    channel_attention: true
    norm_layer: SyncBN
    activation_fn: SiLU
  backbone_output_channels: 768
  heads:
    bodypart:
      type: RTMCCHead
      weight_init: RTMPose
      target_generator:
        type: SimCCGenerator
        input_size: [256, 256]
        smoothing_type: gaussian
        sigma: [5.66, 5.66]
        simcc_split_ratio: 2.0
        label_smooth_weight: 0.0
        normalize: false
      criterion:
        x:
          type: KLDiscreteLoss
          use_target_weight: true
          beta: 10.0
          label_softmax: true
        y:
          type: KLDiscreteLoss
          use_target_weight: true
          beta: 10.0
          label_softmax: true
      predictor:
        type: SimCCPredictor
        simcc_split_ratio: 2.0
      input_size: [256, 256]
      in_channels: 768
      out_channels: "num_bodyparts"
      in_featuremap_size: [8, 8]  # input_size / backbone stride
      simcc_split_ratio: 2.0
      final_layer_kernel_size: 7
      gau_cfg:
        hidden_dims: 256
        s: 128
        expansion_factor: 2
        dropout_rate: 0
        drop_path: 0.0
        act_fn: "SiLU"
        use_rel_bias: false
        pos_enc: False
